#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else false; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any, with write_env's quoting undone.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line value sq="'\\''"; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  value="${line#*=}"
  if [[ "$value" == \'*\' ]]; then value="${value:1:${#value}-2}"; value="${value//"$sq"/\'}"; fi
  printf '%s' "$value"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret), edited
# with Readline. Fails at EOF with no input.
ask() {
  local key="$1" prompt="$2" current input s=$'\001' e=$'\002' p rc=0
  current=$(_existing "$key" || true)
  # Readline needs the colour codes wrapped in \001..\002 to place the cursor.
  p="  $s$BOLD$e$prompt$s$RESET$e "
  [[ -n "$current" ]] && p+="$s$DIM$e[Enter keeps current]$s$RESET$e "
  read -e -r -p "$p" input || rc=1
  if (( rc )) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input rc=0
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || rc=1
  printf '\n'
  if (( rc )) && [[ -z "$input" ]]; then return 1; fi
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY='VALUE' into ENV_FILE (replaces any existing
# line). Idempotent. Creates ENV_FILE at mode 0600; writes through a symlink
# and keeps an existing file's mode.
write_env() {
  local key="$1" value="$2" tmp sq="'\\''"
  [[ -e "$ENV_FILE" ]] || (umask 077 && : > "$ENV_FILE")
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf "%s='%s'\n" "$key" "${value//\'/$sq}" >> "$tmp"
  cat "$tmp" > "$ENV_FILE"
  rm -f "$tmp"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Stop inherited shell tracing before any secret is collected.
set +x
TOTAL_STAGES=5
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${script_dir}/setup.local.env"
GCLOUD_BIN=""
trap 'unset API_DATABASE_URL_PAYLOAD API_SUPABASE_SECRET_KEY_PAYLOAD' EXIT

locate_gcloud() {
  GCLOUD_BIN="$(command -v gcloud || true)"
  if [[ -z "$GCLOUD_BIN" && -n "${HOME:-}" && -x "${HOME}/google-cloud-sdk/bin/gcloud" ]]; then
    GCLOUD_BIN="${HOME}/google-cloud-sdk/bin/gcloud"
  fi
  [[ -n "$GCLOUD_BIN" ]]
}

ask_default() {
  local key="$1" prompt="$2" default_value="$3" current input
  current=$(_existing "$key" || true)
  [[ -n "$current" ]] || current="$default_value"
  printf '  %s [Enter keeps %s]: ' "$prompt" "$current"
  read -e -r input || return 1
  [[ -n "$input" ]] || input="$current"
  printf -v "$key" '%s' "$input"
}

ask_fresh() {
  local key="$1" prompt="$2" input
  printf '  %s ' "$prompt"
  read -e -r input || return 1
  printf -v "$key" '%s' "$input"
}

secret_name_is_valid() {
  [[ "$1" =~ ^[a-zA-Z0-9_-]{1,255}$ ]]
}

secret_names_are_distinct() {
  [[ "$1" != "$2" && "$1" != "$3" && "$2" != "$3" ]]
}

iso_date_is_valid() {
  local value="$1" normalized
  if normalized="$(date -j -f '%Y-%m-%d' "$value" '+%Y-%m-%d' 2>/dev/null)"; then
    [[ "$normalized" == "$value" ]]
  elif normalized="$(date -d "$value" '+%Y-%m-%d' 2>/dev/null)"; then
    [[ "$normalized" == "$value" ]]
  else
    return 1
  fi
}

ensure_secret_resource() {
  local name="$1"
  if "$GCLOUD_BIN" secrets describe "$name" --project="$GCP_PROJECT_ID" --format='value(name)' >/dev/null 2>&1; then
    return 0
  fi
  "$GCLOUD_BIN" secrets create "$name" \
    --replication-policy=user-managed \
    --locations="$GCP_REGION" \
    --project="$GCP_PROJECT_ID" \
    --quiet >/dev/null 2>&1
}

add_secret_version() {
  local name="$1" payload="$2" version_key="$3" name_key="$4" version_resource version
  if ! version_resource="$(printf '%s' "$payload" | "$GCLOUD_BIN" secrets versions add "$name" \
    --data-file=- --project="$GCP_PROJECT_ID" --format='value(name)' 2>/dev/null)"; then
    return 1
  fi
  version="${version_resource##*/}"
  if [[ ! "$version" =~ ^[0-9]+$ ]]; then
    version_resource="$("$GCLOUD_BIN" secrets versions list "$name" --project="$GCP_PROJECT_ID" \
      --filter='state=ENABLED' --sort-by='~createTime' --limit=1 --format='value(name)' 2>/dev/null || true)"
    version="${version_resource##*/}"
  fi
  [[ "$version" =~ ^[0-9]+$ ]] || return 1
  write_env "$name_key" "$name"
  write_env "$version_key" "$version"
}

valid_recorded_version() {
  local name="$1" version="$2"
  [[ "$version" =~ ^[0-9]+$ ]] || return 1
  "$GCLOUD_BIN" secrets versions describe "$version" --secret="$name" \
    --project="$GCP_PROJECT_ID" --format='value(name)' >/dev/null 2>&1
}

banner "Superkalan GCP setup preflight"
say "This wizard records local configuration and, only after confirmation, Secret Manager versions."
say "It never creates a VM, firewall rule, image, Cloud Run service, or deployment."
note "Secret payloads are entered hidden and are never written to the local config file."
pause "Ready to start?"

stage "GCP project and network discovery"
if locate_gcloud; then
  if active_project="$("$GCLOUD_BIN" config get-value project 2>/dev/null)" &&
    [[ -n "$active_project" && "$active_project" != "unset" && "$active_project" != "(unset)" ]]; then
    say "Active gcloud project: $active_project"
    if confirm "Use this active project for the setup wizard?"; then
      GCP_PROJECT_ID="$active_project"
      GCP_REGION="asia-southeast1"
      GCP_DISCOVERY_STATUS="READ_ONLY_COMPLETE"
      write_env GCP_PROJECT_ID "$GCP_PROJECT_ID"
      write_env GCP_REGION "$GCP_REGION"

      if networks="$("$GCLOUD_BIN" compute networks list --project="$GCP_PROJECT_ID" --format='value(name)' 2>/dev/null)"; then
        say "Networks found (discovery only):"
        [[ -n "$networks" ]] && printf '%s\n' "$networks" || say "  none returned"
        network_record="$(printf '%s\n' "$networks" | tr '\n' ';' | sed 's/;$//')"
        write_env GCP_DISCOVERED_NETWORKS "$network_record"
      else
        warn "Could not list networks with this gcloud identity; do not assume a network."
        GCP_DISCOVERY_STATUS="INCOMPLETE"
      fi

      if subnets="$("$GCLOUD_BIN" compute networks subnets list --project="$GCP_PROJECT_ID" \
        --regions="$GCP_REGION" --format='value(name,network.basename(),ipCidrRange)' 2>/dev/null)"; then
        say "Subnets in $GCP_REGION (discovery only):"
        [[ -n "$subnets" ]] && printf '%s\n' "$subnets" || say "  none returned"
        subnet_record="$(printf '%s\n' "$subnets" | tr '\n' ';' | sed 's/;$//')"
        write_env GCP_DISCOVERED_SINGAPORE_SUBNETS "$subnet_record"
      else
        warn "Could not list Singapore subnets with this identity."
        GCP_DISCOVERY_STATUS="INCOMPLETE"
      fi

      if firewalls="$("$GCLOUD_BIN" compute firewall-rules list --project="$GCP_PROJECT_ID" \
        --format='table(name,network.basename(),direction,sourceRanges.list(),allowed)' 2>/dev/null)"; then
        say "Current firewall inventory (review it; this wizard changes no rules):"
        [[ -n "$firewalls" ]] && printf '%s\n' "$firewalls" || say "  none returned"
      else
        warn "Could not inspect firewall rules; security review is still required."
      fi
      write_env GCP_NETWORK_REVIEW_REQUIRED YES
      warn "Discovered networks are not approved deployment settings. The last workspace inventory found broad public ingress on the default VPC; review the live firewall output and resolve a safe network before provisioning."
      write_env GCP_DISCOVERY_STATUS "${GCP_DISCOVERY_STATUS:-READ_ONLY_COMPLETE}"
    else
      SKIPPED+=("GCP project/network discovery; select the intended project and rerun")
      warn "No project was selected; this wizard will not change gcloud's active project."
    fi
  else
    SKIPPED+=("GCP project/network discovery; configure gcloud and rerun")
    warn "No active gcloud project was found. This wizard will not select one for you."
  fi
else
  SKIPPED+=("GCP project/network discovery; install or expose gcloud on PATH")
  warn "gcloud was not found. Billing and device checks can continue, but GCP secret writes will be skipped."
fi

stage "Trial credit and full-window cost review"
open_url "https://console.cloud.google.com/billing/overview"
step "Select the billing account and confirm it is still on the Free Trial, not upgraded to paid billing for this plan. Then recheck current credit, remaining days, and expiry; earlier reported values are not assumed current."
if confirm "Does Billing Overview still show the Free Trial, with no paid upgrade for this plan?"; then
  GCP_BILLING_MODE="FREE_TRIAL_REPORTED"
else
  GCP_BILLING_MODE="PAID_OR_UNKNOWN"
  warn "GCP resource writes will be skipped unless the Free Trial status is verified."
fi
ask_fresh GCP_CREDIT_BALANCE_USD "Remaining trial credit in USD (recheck now):"
while [[ ! "$GCP_CREDIT_BALANCE_USD" =~ ^[0-9]+([.][0-9]{1,2})?$ ]]; do
  warn "Enter a non-negative amount, for example 300 or 300.00."
  ask_fresh GCP_CREDIT_BALANCE_USD "Remaining trial credit in USD (recheck now):"
done
ask_fresh GCP_CREDIT_DAYS_REMAINING "Days remaining (recheck now):"
while [[ ! "$GCP_CREDIT_DAYS_REMAINING" =~ ^[0-9]+$ ]]; do
  warn "Enter the whole number of days shown in Billing Overview."
  ask_fresh GCP_CREDIT_DAYS_REMAINING "Days remaining (recheck now):"
done
ask_fresh GCP_CREDIT_EXPIRY_DATE "Credit expiry date (YYYY-MM-DD; recheck now):"
while [[ ! "$GCP_CREDIT_EXPIRY_DATE" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] || ! iso_date_is_valid "$GCP_CREDIT_EXPIRY_DATE"; do
  warn "Use the date shown in Billing Overview in YYYY-MM-DD format."
  ask_fresh GCP_CREDIT_EXPIRY_DATE "Credit expiry date (YYYY-MM-DD; recheck now):"
done
ask_fresh GCP_RESOURCE_STOP_DATE "Planned export/stop date before expiry (YYYY-MM-DD, or TBD):"
current_date="$(date +%Y-%m-%d)"
if [[ "$GCP_RESOURCE_STOP_DATE" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] &&
  iso_date_is_valid "$GCP_RESOURCE_STOP_DATE" &&
  "$GCP_RESOURCE_STOP_DATE" > "$current_date" &&
  [[ "$GCP_RESOURCE_STOP_DATE" < "$GCP_CREDIT_EXPIRY_DATE" ]]; then
  GCP_CUTOFF_GATE="BEFORE_CREDIT_EXPIRY"
else
  GCP_CUTOFF_GATE="NEEDS_OWNER_DECISION"
  warn "Choose and record a valid export/stop date strictly before credit expiry before provisioning."
fi

open_url "https://cloud.google.com/products/calculator"
step "Estimate the entire planned cost through the trial-credit expiry: 24/7 VM, disk, external IPv4, Cloud Run, network, image storage, logs, backup and restore testing."
step "Enter the latest full-window estimate for the actual request count and combined API + NGINX container resources. Older estimates are obsolete; this is a draft, not approval to provision. Preserve a separate reserve."
ask_fresh GCP_COST_ESTIMATE_USD "Full-window estimated cost (USD; recalculate now):"
while [[ ! "$GCP_COST_ESTIMATE_USD" =~ ^[0-9]+([.][0-9]{1,2})?$ ]]; do
  warn "Enter a non-negative amount, for example 120 or 120.00."
  ask_fresh GCP_COST_ESTIMATE_USD "Full-window estimated cost (USD; recalculate now):"
done
ask_fresh GCP_CREDIT_RESERVE_USD "Credit to keep unallocated as reserve (USD; review now):"
while [[ ! "$GCP_CREDIT_RESERVE_USD" =~ ^[0-9]+([.][0-9]{1,2})?$ ]]; do
  warn "Enter a non-negative amount, for example 150 or 150.00."
  ask_fresh GCP_CREDIT_RESERVE_USD "Credit to keep unallocated as reserve (USD; review now):"
done
if awk -v balance="$GCP_CREDIT_BALANCE_USD" -v days="$GCP_CREDIT_DAYS_REMAINING" \
  -v estimate="$GCP_COST_ESTIMATE_USD" -v reserve="$GCP_CREDIT_RESERVE_USD" \
  'BEGIN { exit !(balance > 0 && days > 0 && estimate > 0 && reserve > 0 && (estimate + reserve) <= balance) }'; then
  GCP_CREDIT_ARITHMETIC_GATE="WITHIN_REPORTED_BALANCE"
  say "Estimate plus reserve fits the entered balance arithmetically."
else
  GCP_CREDIT_ARITHMETIC_GATE="EXCEEDS_REPORTED_BALANCE"
  warn "Estimate plus reserve exceeds the reported balance. Do not provision unless a new smaller reviewed plan fits."
fi
write_env GCP_CREDIT_BALANCE_USD "$GCP_CREDIT_BALANCE_USD"
write_env GCP_CREDIT_DAYS_REMAINING "$GCP_CREDIT_DAYS_REMAINING"
write_env GCP_CREDIT_EXPIRY_DATE "$GCP_CREDIT_EXPIRY_DATE"
write_env GCP_RESOURCE_STOP_DATE "$GCP_RESOURCE_STOP_DATE"
write_env GCP_CUTOFF_GATE "$GCP_CUTOFF_GATE"
write_env GCP_BILLING_MODE "$GCP_BILLING_MODE"
write_env GCP_COST_ESTIMATE_USD "$GCP_COST_ESTIMATE_USD"
write_env GCP_CREDIT_RESERVE_USD "$GCP_CREDIT_RESERVE_USD"
write_env GCP_CREDIT_ARITHMETIC_GATE "$GCP_CREDIT_ARITHMETIC_GATE"
write_env GCP_COST_REVIEW_STATUS NEEDS_FINAL_OWNER_APPROVAL
write_env GCP_BUDGET_ALERTS_STATUS NEEDS_MANUAL_SETUP
say "This records a draft cost review only. It does not approve provisioning or paid continuation."
note "After the owner approves the final estimate, create a project-scoped Billing budget alert before provisioning. Alerts notify; they do not automatically stop Compute Engine charges."

stage "Verify the SinoTrack ST-901 variant"
open_url "https://www.traccar.org/devices/"
step "Check the tracker label or ask the seller which exact variant/protocol the unit supports. The product listing alone only confirms ST-901."
step "Traccar's catalog distinguishes standard ST-901 (H02/TCP 5013) and ST-901 A+ (JT808/TCP 5015). Do not open a firewall port in this wizard."
ask GCP_ST901_VARIANT "Enter standard, a+, or unknown (lowercase):"
variant_input="$(printf '%s' "$GCP_ST901_VARIANT" | tr '[:upper:]' '[:lower:]')"
while [[ "$variant_input" != "standard" && "$variant_input" != "a+" && "$variant_input" != "unknown" ]]; do
  warn "Enter standard, a+, or unknown."
  ask GCP_ST901_VARIANT "Enter standard, a+, or unknown (lowercase):"
  variant_input="$(printf '%s' "$GCP_ST901_VARIANT" | tr '[:upper:]' '[:lower:]')"
done
if [[ "$variant_input" == "standard" ]]; then
  candidate_protocol="H02"
  candidate_port="5013"
  variant_label="standard ST-901"
elif [[ "$variant_input" == "a+" ]]; then
  candidate_protocol="JT808"
  candidate_port="5015"
  variant_label="ST-901 A+"
else
  candidate_protocol="unconfirmed"
  candidate_port=""
  variant_label="unknown ST-901 variant"
fi
if [[ -n "$candidate_port" ]] && confirm "Has the seller/unit label confirmed $variant_label, $candidate_protocol, TCP $candidate_port?"; then
  GCP_ST901_PORT_VERIFIED=YES
else
  GCP_ST901_PORT_VERIFIED=NO
  [[ -n "$candidate_port" ]] && warn "The candidate is recorded as unverified; do not configure or open it."
fi
write_env GCP_ST901_VARIANT "$variant_label"
write_env GCP_ST901_PROTOCOL_CANDIDATE "$candidate_protocol"
write_env GCP_ST901_PORT_CANDIDATE "$candidate_port"
write_env GCP_ST901_PORT_VERIFIED "$GCP_ST901_PORT_VERIFIED"

stage "Existing Supabase configuration and Secret Manager"
open_url "https://supabase.com/dashboard"
open_url "https://supabase.com/docs/guides/database/connecting-to-postgres"
open_url "https://supabase.com/docs/guides/database/connecting-to-postgres/pooling-and-limits"
open_url "https://supabase.com/docs/guides/platform/ssl-enforcement"
open_url "https://supabase.com/docs/guides/getting-started/api-keys"
step "In the existing project, open Settings → API Keys and copy the current sb_publishable_ key (not the legacy anon key)."
ask SUPABASE_URL "Supabase project URL (HTTPS origin only):"
while [[ ! "$SUPABASE_URL" =~ ^https://[A-Za-z0-9.-]+(:[0-9]+)?/?$ ]]; do
  warn "Enter the HTTPS project origin only, such as https://project-ref.supabase.co."
  ask SUPABASE_URL "Supabase project URL (HTTPS origin only):"
done
SUPABASE_URL="${SUPABASE_URL%/}"
ask SUPABASE_PUBLISHABLE_KEY "Current Supabase publishable key (sb_publishable_...):"
while [[ "$SUPABASE_PUBLISHABLE_KEY" != sb_publishable_* ]]; do
  warn "The API deployment requires the current sb_publishable_ key format."
  ask SUPABASE_PUBLISHABLE_KEY "Current Supabase publishable key (sb_publishable_...):"
done
write_env SUPABASE_URL "$SUPABASE_URL"
write_env SUPABASE_PUBLISHABLE_KEY "$SUPABASE_PUBLISHABLE_KEY"

step "Before choosing a Postgres URI, confirm the connection mode and Cloud Run connection/pool budget. The current manifest allows 2 API instances and TypeORM allows 5 Postgres connections per instance (up to 10 from this service); include other project clients in Supabase's limits. Supabase Dashboard → Connect shows the connection options."
if ! confirm "Have you reviewed and selected a Supabase connection mode and verified the connection budget for the planned Cloud Run scale?"; then
  write_env SUPABASE_SECRET_UPLOAD_STATUS DEFERRED_CONNECTION_BUDGET_REVIEW
  SKIPPED+=("Supabase database URL, secret key and CA upload; settle connection mode/pool budget, then rerun this wizard")
  warn "No database URL or secret was collected or uploaded."
else
  if [[ "${GCP_BILLING_MODE:-}" != "FREE_TRIAL_REPORTED" ]]; then
    write_env SUPABASE_SECRET_UPLOAD_STATUS DEFERRED_FREE_TRIAL_NOT_CONFIRMED
    SKIPPED+=("Supabase Secret Manager upload; verify the billing account is still on Free Trial")
    warn "No GCP write will be made until Free Trial status is confirmed."
  elif [[ "${GCP_CREDIT_ARITHMETIC_GATE:-}" != "WITHIN_REPORTED_BALANCE" || "${GCP_CUTOFF_GATE:-}" != "BEFORE_CREDIT_EXPIRY" ]]; then
    write_env SUPABASE_SECRET_UPLOAD_STATUS DEFERRED_COST_OR_CUTOFF_GATE
    SKIPPED+=("Supabase Secret Manager upload; enter a cost-plus-reserve amount within the refreshed credit and a stop date before expiry")
    warn "No GCP write will be made while the draft estimate/reserve or cutoff does not fit the Free Trial window."
  elif [[ -z "${GCP_PROJECT_ID:-}" || -z "${GCLOUD_BIN:-}" ]]; then
    write_env SUPABASE_SECRET_UPLOAD_STATUS DEFERRED_GCLOUD_PROJECT
    SKIPPED+=("Supabase Secret Manager upload; select a gcloud project and rerun")
    warn "The project and gcloud CLI are required before any Secret Manager write."
  elif ! "$GCLOUD_BIN" secrets list --project="$GCP_PROJECT_ID" --format='value(name)' >/dev/null 2>&1; then
    write_env SUPABASE_SECRET_UPLOAD_STATUS DEFERRED_SECRET_MANAGER_ACCESS
    SKIPPED+=("Supabase Secret Manager upload; enable/access Secret Manager manually, then rerun")
    warn "Secret Manager is unavailable to this identity or its API is not enabled; the wizard will not enable services automatically."
  else
    reuse_recorded="NO"
    previous_upload_status="$(_existing SUPABASE_SECRET_UPLOAD_STATUS || true)"
    old_db_name="$(_existing DATABASE_SECRET_NAME || true)"
    old_db_version="$(_existing DATABASE_SECRET_VERSION || true)"
    old_key_name="$(_existing SUPABASE_SECRET_KEY_SECRET_NAME || true)"
    old_key_version="$(_existing SUPABASE_SECRET_KEY_SECRET_VERSION || true)"
    old_ca_name="$(_existing SUPABASE_DB_CA_SECRET_NAME || true)"
    old_ca_version="$(_existing SUPABASE_DB_CA_SECRET_VERSION || true)"
    old_secret_project="$(_existing GCP_SECRET_MANAGER_PROJECT_ID || true)"
    case "$previous_upload_status" in
      WRITE_IN_PROGRESS|DATABASE_URL_UPLOAD_FAILED|PARTIAL_*)
        reuse_recorded="BLOCKED_PARTIAL"
        warn "A prior Secret Manager upload was partial or ambiguous. Inspect version metadata and reconcile the recorded versions manually before retrying; this wizard will not append duplicates."
        SKIPPED+=("Supabase Secret Manager retry blocked by prior partial upload; reconcile Secret Manager metadata first")
        ;;
    esac
    if [[ "$reuse_recorded" != "BLOCKED_PARTIAL" && -n "$old_db_name" && -n "$old_db_version" && -n "$old_key_name" && -n "$old_key_version" && -n "$old_ca_name" && -n "$old_ca_version" ]]; then
      if [[ "$old_secret_project" == "$GCP_PROJECT_ID" ]]; then
        say "The local config records existing Secret Manager resource names and version numbers; secret values are never read by this wizard."
        if confirm "Do these recorded versions match the currently selected Supabase project, and should they be reused without reading or rotating secret values?" &&
          valid_recorded_version "$old_db_name" "$old_db_version" &&
          valid_recorded_version "$old_key_name" "$old_key_version" &&
          valid_recorded_version "$old_ca_name" "$old_ca_version"; then
          reuse_recorded="YES"
          say "Recorded versions exist. Reusing them; no secret payload will be read or written."
        else
          warn "Recorded versions were not reused; this path will add new versions after another confirmation."
        fi
      else
        warn "Recorded secret versions belong to another or unknown GCP project; they will not be reused here."
      fi
    fi

    if [[ "$reuse_recorded" == "BLOCKED_PARTIAL" ]]; then
      :
    elif [[ "$reuse_recorded" == "YES" ]]; then
      write_env SUPABASE_SECRET_UPLOAD_STATUS READY_REUSED_RECORDED_VERSIONS
    else
      ask_secret API_DATABASE_URL_PAYLOAD "Paste the approved PostgreSQL connection URI (input is hidden):"
      while [[ ! "$API_DATABASE_URL_PAYLOAD" =~ ^(postgres|postgresql)://[^[:space:]]+$ ]]; do
        warn "The connection URI must begin postgres:// or postgresql:// and contain no spaces."
        ask_secret API_DATABASE_URL_PAYLOAD "Paste the approved PostgreSQL connection URI (input is hidden):"
      done
      ask_secret API_SUPABASE_SECRET_KEY_PAYLOAD "Paste the current Supabase secret key (sb_secret_..., input is hidden):"
      while [[ "$API_SUPABASE_SECRET_KEY_PAYLOAD" != sb_secret_* ]]; do
        warn "Use the current sb_secret_ key, not the legacy service_role key."
        ask_secret API_SUPABASE_SECRET_KEY_PAYLOAD "Paste the current Supabase secret key (sb_secret_..., input is hidden):"
      done
      step "Download the database server root CA from Database Settings → SSL Configuration → Download Certificate."
      ask SUPABASE_DB_CA_FILE_PATH "Path to the downloaded CA certificate file:"
      while [[ ! -f "$SUPABASE_DB_CA_FILE_PATH" || ! -r "$SUPABASE_DB_CA_FILE_PATH" ]] ||
        ! grep -q -- '-----BEGIN CERTIFICATE-----' "$SUPABASE_DB_CA_FILE_PATH"; do
        warn "Choose a readable PEM CA file containing a certificate. Its contents will not be displayed or stored locally."
        ask SUPABASE_DB_CA_FILE_PATH "Path to the downloaded CA certificate file:"
      done

      ask_default DATABASE_SECRET_NAME "Secret Manager name for DATABASE_URL" "superkalan-api-database-url"
      ask_default SUPABASE_SECRET_KEY_SECRET_NAME "Secret Manager name for SUPABASE_SECRET_KEY" "superkalan-api-supabase-secret-key"
      ask_default SUPABASE_DB_CA_SECRET_NAME "Secret Manager name for the Supabase database CA" "superkalan-api-supabase-db-ca"
      for secret_name in "$DATABASE_SECRET_NAME" "$SUPABASE_SECRET_KEY_SECRET_NAME" "$SUPABASE_DB_CA_SECRET_NAME"; do
        if ! secret_name_is_valid "$secret_name"; then
          warn "Invalid Secret Manager resource name: $secret_name. Use letters, digits, hyphens or underscores."
          SKIPPED+=("Supabase Secret Manager upload; correct invalid secret resource names and rerun")
          break
        fi
      done

      if secret_name_is_valid "$DATABASE_SECRET_NAME" &&
        secret_name_is_valid "$SUPABASE_SECRET_KEY_SECRET_NAME" &&
        secret_name_is_valid "$SUPABASE_DB_CA_SECRET_NAME" &&
        secret_names_are_distinct "$DATABASE_SECRET_NAME" "$SUPABASE_SECRET_KEY_SECRET_NAME" "$SUPABASE_DB_CA_SECRET_NAME"; then
        write_env DATABASE_SECRET_NAME "$DATABASE_SECRET_NAME"
        write_env SUPABASE_SECRET_KEY_SECRET_NAME "$SUPABASE_SECRET_KEY_SECRET_NAME"
        write_env SUPABASE_DB_CA_SECRET_NAME "$SUPABASE_DB_CA_SECRET_NAME"
        write_env SUPABASE_SECRET_UPLOAD_STATUS PENDING_CONFIRMATION
        say "Planned resources in project $GCP_PROJECT_ID, replication location $GCP_REGION:"
        say "  DATABASE_URL → $DATABASE_SECRET_NAME"
        say "  Supabase secret key → $SUPABASE_SECRET_KEY_SECRET_NAME"
        say "  Supabase CA certificate → $SUPABASE_DB_CA_SECRET_NAME"
        warn "Existing resources keep their old versions; this action appends a new immutable version. Review every name before continuing."
        for secret_name in "$DATABASE_SECRET_NAME" "$SUPABASE_SECRET_KEY_SECRET_NAME" "$SUPABASE_DB_CA_SECRET_NAME"; do
          if "$GCLOUD_BIN" secrets describe "$secret_name" --project="$GCP_PROJECT_ID" --format='value(name)' >/dev/null 2>&1; then
            say "Existing resource (a new version will be appended): $secret_name"
          else
            say "New secret with Singapore-only user-managed replication will be created: $secret_name"
          fi
        done
        if confirm "Create any missing regional secret resources and upload these three values now? No secret payload will be printed or saved locally."; then
          write_env GCP_SECRET_MANAGER_PROJECT_ID "$GCP_PROJECT_ID"
          write_env SUPABASE_SECRET_UPLOAD_STATUS WRITE_IN_PROGRESS
          if ensure_secret_resource "$DATABASE_SECRET_NAME" &&
            ensure_secret_resource "$SUPABASE_SECRET_KEY_SECRET_NAME" &&
            ensure_secret_resource "$SUPABASE_DB_CA_SECRET_NAME"; then
            if add_secret_version "$DATABASE_SECRET_NAME" "$API_DATABASE_URL_PAYLOAD" DATABASE_SECRET_VERSION DATABASE_SECRET_NAME; then
              if add_secret_version "$SUPABASE_SECRET_KEY_SECRET_NAME" "$API_SUPABASE_SECRET_KEY_PAYLOAD" SUPABASE_SECRET_KEY_SECRET_VERSION SUPABASE_SECRET_KEY_SECRET_NAME; then
                if version_resource="$("$GCLOUD_BIN" secrets versions add "$SUPABASE_DB_CA_SECRET_NAME" \
                  --data-file="$SUPABASE_DB_CA_FILE_PATH" --project="$GCP_PROJECT_ID" --format='value(name)' 2>/dev/null)"; then
                  ca_version="${version_resource##*/}"
                  if [[ ! "$ca_version" =~ ^[0-9]+$ ]]; then
                    version_resource="$("$GCLOUD_BIN" secrets versions list "$SUPABASE_DB_CA_SECRET_NAME" \
                      --project="$GCP_PROJECT_ID" --filter='state=ENABLED' --sort-by='~createTime' \
                      --limit=1 --format='value(name)' 2>/dev/null || true)"
                    ca_version="${version_resource##*/}"
                  fi
                  if [[ "$ca_version" =~ ^[0-9]+$ ]]; then
                    write_env SUPABASE_DB_CA_SECRET_NAME "$SUPABASE_DB_CA_SECRET_NAME"
                    write_env SUPABASE_DB_CA_SECRET_VERSION "$ca_version"
                    write_env SUPABASE_SECRET_UPLOAD_STATUS READY_NEW_VERSIONS
                  else
                    write_env SUPABASE_SECRET_UPLOAD_STATUS PARTIAL_CA_VERSION_REQUIRES_REVIEW
                    SKIPPED+=("CA secret version number could not be confirmed; inspect Secret Manager metadata before deployment")
                    warn "A CA version may have been uploaded, but its number could not be verified. Do not retry blindly."
                  fi
                else
                  write_env SUPABASE_SECRET_UPLOAD_STATUS PARTIAL_CA_UPLOAD_FAILED
                  SKIPPED+=("Supabase CA secret upload failed; inspect Secret Manager before retrying")
                  warn "The database URL and key versions were already uploaded; CA upload failed. Inspect metadata before retrying."
                fi
              else
                write_env SUPABASE_SECRET_UPLOAD_STATUS PARTIAL_SECRET_KEY_UPLOAD_FAILED
                SKIPPED+=("Supabase secret-key upload failed after the database URL version; inspect Secret Manager before retrying")
                warn "The database URL version may already exist. Inspect metadata before retrying."
              fi
            else
              write_env SUPABASE_SECRET_UPLOAD_STATUS DATABASE_URL_UPLOAD_FAILED
              SKIPPED+=("Database URL secret upload failed; inspect Secret Manager before retrying")
              warn "No subsequent secret was uploaded. Check Secret Manager before retrying."
            fi
          else
            write_env SUPABASE_SECRET_UPLOAD_STATUS DEFERRED_SECRET_RESOURCE_CREATE_FAILED
            SKIPPED+=("One or more Secret Manager resources could not be created; inspect them and rerun")
            warn "A resource creation failed. Any earlier empty secret resources remain; no secret versions were uploaded by this step."
          fi
        else
          write_env SUPABASE_SECRET_UPLOAD_STATUS DEFERRED_USER_DECLINED
          SKIPPED+=("Secret Manager upload; review names and rerun when ready")
          say "No Secret Manager write was made."
        fi
      else
        write_env SUPABASE_SECRET_UPLOAD_STATUS DEFERRED_INVALID_OR_DUPLICATE_SECRET_NAME
        warn "Secret resource names must be valid and distinct so each API secret has a separate Secret Manager resource."
      fi
      unset API_DATABASE_URL_PAYLOAD API_SUPABASE_SECRET_KEY_PAYLOAD
    fi
  fi
fi

stage "Final preflight and stop"
say "The setup wizard has finished collecting preflight information. It has not provisioned or deployed the application."
note "Before any release: resolve the secure VPC and firewall design; approve the exact total-cost estimate/reserve and cutoff; create and verify Billing budget alerts; verify the ST-901 port; review the Supabase connection/pool budget; verify the database migration state; test build, containers, backup and restore; then separately approve deployment."
warn "This wizard will not create a VM, firewall rule, image, Cloud Run service, billing budget, or release. It does not approve paid continuation after trial credits end."
say "Local non-secret setup values: $ENV_FILE"
finish
